# This is a basic workflow that is manually triggered

name: Set Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - FullV2-RNT
    - origin/FullV2-RNT
    - FullV2 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout  
      uses: actions/checkout@v2  
      with:  
         fetch-depth: 0  
      
    - name: Version  
      id: version  
      uses: kenzouno1/tag-version@v1  
      with:  
         production-branch: FullV2-RNT
